{% set name = "synopticpy" %}
{% set version = "2024.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44ec3e84399510d9c10c50726a80e6b1829662837b4d6f412db0df74702d103a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - PYTHONIOENCODING=utf8

requirements:
  host:
    - pip
    - python 3.11
    - hatchling
    - hatch-vcs

  run:
    - numpy
    - polars[style,plot,timezone] >=1.9.0
    - python >=3.11
    - requests
    - toml
    - matplotlib-base

test:
  commands:
    - pip check
  imports:
    #- synoptic.services  # Askes for User input, so don't do this.
  requires:
    - pip

about:
  home: https://github.com/blaylockbk/SynopticPy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Get mesonet data from the Synoptic API.
  description: |
    Retrieve mesonet weather data as Polars DataFrames from Synoptic's Weather API.
  doc_url: https://SynopticPy.readthedocs.io/
  dev_url: https://github.com/blaylockbk/SynopticPy

extra:
  recipe-maintainers:
    - blaylockbk
