{% set python_min = "3.11" %}
{% set name = "synopticpy" %}
{% set version = "2025.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 29131d23cc30cd24a56292a63784b4c390eea337a667e0738fb413cae0a7e32d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - PYTHONIOENCODING=utf8

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs

  run:
    - numpy
    - polars[style,plot,timezone] >=1.9.0
    - python >={{ python_min }}
    - requests
    - toml
    - matplotlib-base

test:
  commands:
    - pip check
  imports:
    #- synoptic.services  # Askes for User input, so don't do this.
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/blaylockbk/SynopticPy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Get mesonet data from the Synoptic API.
  description: |
    Retrieve mesonet weather data as Polars DataFrames from Synoptic's Weather API.
  doc_url: https://SynopticPy.readthedocs.io/
  dev_url: https://github.com/blaylockbk/SynopticPy

extra:
  recipe-maintainers:
    - blaylockbk
